export enum ErrorCodes {
  // General
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // Database
  DATABASE_ERROR = 'DATABASE_ERROR',
  DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
  DB_CONNECTION_ERROR = 'DB_CONNECTION_ERROR',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',

  // Rate limit
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // Other
  NOT_FOUND = 'NOT_FOUND',
  FOREIGN_KEY_CONSTRAINT = 'FOREIGN_KEY_CONSTRAINT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export default ErrorCodes;